#!/usr/bin/env bash
# Purpose: Draft the next CHANGELOG.md section from git commits since the last tag.
#
# Reads git log from the last tag to HEAD, groups commits by conventional
# commit prefix (feat/fix/chore/docs/refactor/test/ci/perf/build), and
# renders a draft section in the Keep a Changelog format already used by
# dream-server/CHANGELOG.md.
#
# Expects:
#   git  — must be available and run from inside a git repository
#
# Provides:
#   Stdout or --output FILE — a ready-to-paste CHANGELOG.md section
#   Exit 0  — always (reporting tool, not a gate)
#
# Usage:
#   scripts/gen-changelog-draft.sh [--output FILE] [--version VERSION]
#
# Options:
#   --output FILE     Write draft to FILE instead of stdout
#   --version VERSION Use VERSION as the release heading (default: [Unreleased])
#
# Modder notes:
#   Prefix-to-section mapping is in the SECTION_MAP below.  Add new prefixes
#   by appending entries to the map.  Commits with unrecognised prefixes fall
#   into "Changed".
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

OUTPUT_FILE=""
VERSION=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)  OUTPUT_FILE="$2"; shift 2 ;;
        --version) VERSION="$2";     shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

command -v git >/dev/null 2>&1 || { echo "gen-changelog-draft: git is required" >&2; exit 1; }

cd "$ROOT_DIR"

# ── Resolve range ────────────────────────────────────────────────────────────
LAST_TAG="$(git describe --tags --abbrev=0 2>/dev/null || true)"
if [[ -z "$LAST_TAG" ]]; then
    RANGE="HEAD"
    SINCE_MSG="beginning of history"
else
    RANGE="${LAST_TAG}..HEAD"
    SINCE_MSG="since ${LAST_TAG}"
fi

# ── Section label mapping (conventional commit prefix → Keep a Changelog heading)
declare -A SECTION_MAP=(
    [feat]="Added"
    [feature]="Added"
    [add]="Added"
    [fix]="Fixed"
    [bugfix]="Fixed"
    [hotfix]="Fixed"
    [docs]="Changed"
    [doc]="Changed"
    [refactor]="Changed"
    [perf]="Changed"
    [chore]="Changed"
    [ci]="Changed"
    [build]="Changed"
    [test]="Changed"
    [revert]="Fixed"
    [security]="Security"
    [deprecat]="Deprecated"
    [remov]="Removed"
    [break]="Changed"
)

declare -A SECTIONS  # heading → newline-delimited bullets

_bucket() {
    local subject="$1"
    # Extract prefix: "feat(scope): msg" or "feat: msg" or "Feat msg"
    local prefix
    prefix=$(echo "$subject" | sed -E 's/^([A-Za-z]+)[(:!].*/\1/' | tr '[:upper:]' '[:lower:]')

    local heading="Changed"  # default bucket
    for key in "${!SECTION_MAP[@]}"; do
        if [[ "$prefix" == "$key"* ]]; then
            heading="${SECTION_MAP[$key]}"
            break
        fi
    done
    echo "$heading"
}

_clean_subject() {
    local s="$1"
    # Strip conventional commit prefix + optional scope
    s=$(echo "$s" | sed -E 's/^[A-Za-z]+(\([^)]*\))?[!]?:[[:space:]]*//')
    # Capitalise first letter
    s="${s^}"
    echo "$s"
}

# ── Read commits ─────────────────────────────────────────────────────────────
commit_count=0
while IFS='|' read -r hash subject; do
    [[ -z "$hash" ]] && continue
    heading=$(_bucket "$subject")
    bullet="- $(_clean_subject "$subject") (\`${hash:0:7}\`)"
    SECTIONS[$heading]="${SECTIONS[$heading]:-}${bullet}\n"
    commit_count=$((commit_count + 1))
done < <(git log "$RANGE" --pretty=format:'%h|%s' 2>/dev/null || true)

# ── Render ────────────────────────────────────────────────────────────────────
TODAY="$(date +%Y-%m-%d)"
if [[ -n "$VERSION" ]]; then
    HEADING="## [${VERSION}] - ${TODAY}"
else
    HEADING="## [Unreleased]"
fi

{
    echo "$HEADING"
    echo ""

    if [[ $commit_count -eq 0 ]]; then
        echo "_(No commits found ${SINCE_MSG})_"
    else
        # Emit sections in a stable order matching Keep a Changelog convention
        for section in "Added" "Changed" "Deprecated" "Removed" "Fixed" "Security"; do
            [[ -z "${SECTIONS[$section]:-}" ]] && continue
            echo "### ${section}"
            echo ""
            # Print bullets, de-duplicating identical lines
            echo -e "${SECTIONS[$section]}" | sort -u | grep -v '^$'
            echo ""
        done
    fi

    echo "---"
    echo "<!-- Generated by scripts/gen-changelog-draft.sh on ${TODAY} (${SINCE_MSG}) -->"
} | if [[ -n "$OUTPUT_FILE" ]]; then
    tee "$OUTPUT_FILE" >/dev/null
    echo "Draft written to: $OUTPUT_FILE" >&2
else
    cat
fi

if [[ $commit_count -gt 0 ]]; then
    echo "" >&2
    echo "[gen-changelog-draft] Grouped ${commit_count} commits from ${SINCE_MSG}" >&2
fi
